### ISSUE TITLE
Lua error occured

### ISSUE THREAD

**Issue by WetU** [silverwind/idTip#32] opened 2017-09-03 18:31 UTC
2x idTip\idTip-7.0.6.lua:118: bad argument #1 to 'gmatch' (string expected, got nil)
[C]: in function `gmatch'
idTip\idTip-7.0.6.lua:118: in function <idTip\idTip.lua:107>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...faceAdiBags\libs\AceHook-3.0\AceHook-3.0-8.lua:95: in function <...faceAdiBags\libs\AceHook-3.0\AceHook-3.0.lua:87>
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
FrameXML\ContainerFrame.lua:1149: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
InCombatSkipped

**Comment by silverwind** [comment] 2017-09-04 16:30
I was not able to reproduce it, but I've added a check that should prevent this error. What did you do before this error happened? Hover over anything?

**Comment by WetU** [comment] 2017-09-04 16:52
I opened my container bags and hover over items in my bags.
I think this error is related with artifact power items.

**Comment by WetU** [comment] 2017-09-04 17:31
Hmm... non-artifact power items has same error.
It seems to occur before AdiBags bag update when opened bags.

**Comment by silverwind** [comment] 2017-09-04 18:50
Sounds like some bad interaction with AdiBags, I will test that later. Certainly didn't see these errors with OneBag.

**Comment by WetU** [comment] 2017-09-04 18:58
I confirmed it occurs when Adibags's hooked function is not ended yet.

**Comment by silverwind** [comment] 2018-07-14 09:14
This should be fixed, the `gmatch` is guarded against nil.

**Closed by silverwind** 2018-07-14 09:14 UTC
